PRODUCT_PROPERTY_OVERRIDES +=  \
    103.0.0.(00AV) \
    dalvik.vm.dex2oat-threads=4 \
    dalvik.vm.heapgrowthlimit=384m \
    dalvik.vm.heapmaxfree=8m \
    dalvik.vm.heapminfree=2m \
    dalvik.vm.heapsize=512m \
    dalvik.vm.heapstartsize=8m \
    dalvik.vm.heaptargetutilization=0.75 \
    dalvik.vm.image-dex2oat-threads=4 \
    debug.sf.disable_backpressure = 1 \
    debug.sf.latch_unsignaled = 1 \
    hw.lcd.density=480 \
    keyguard.no_require_sim=true \
    persist.ai.timedebug.enable=false \
    persist.kirin.media.hires.enable=true \
    persist.kirin.media.lowlatency.enable=false \
    persist.kirin.media.offload.enable=true \
    persist.kirin.media.usbvoice.enable=true \
    persist.kirin.media.usbvoice.name=USB-Audio - HUAWEI GLASS \
    persist.kirin.touch_vsync_opt = 1 \
    persist.rog_feature=1 \
    persist.vendor.touch_move_opt = 1 \
    persist.vendor.touchevent_opt = 1 \
    ro.board.platform=kirin970 \
    ro.bt.bdaddr_path=/data/vendor/bluedroid/macbt \
    ro.carrier=unknown \
    ro.comp.chipset_version=Chipset-BOSTON 103.0.0.(00AV) \
    ro.config.hiaiversion=100.151.020.100 \
    ro.config.hw_navigationbar=true \
    ro.config.hw_volte_on=true \
    ro.config.vol_steps=15 \
    ro.control_privapp_permissions=enforce \
    ro.kirin.product.platform=kirin970 \
    ro.netflix.bsp_rev=KIRIN970-15244-1 \
    ro.opengles.version=196610 \
    ro.product.board=kirin970 \
    ro.product.vendor.brand=kirin970 \
    ro.product.vendor.device=kirin970 \
    ro.product.vendor.manufacturer=HUAWEI \
    ro.product.vendor.model=kirin970 \
    ro.product.vendor.name=kirin970 \
    ro.sf.lcd_density=480 \
    ro.vendor.build.display.id=Chipset-BOSTON \
    ro.vendor.build.id=QP1A.190711.020 \
    ro.vendor.build.tags=release-keys \
    ro.vendor.build.type=user \
    ro.vendor.build.version.incremental=20230217122435 \
    ro.vendor.config.board_ipa = true \
    ro.vendor.config.hw_music_lp=true \
    ro.vendor.config.music_lp_vol=true \
    ro.vendor.config.perfgenius = true \
    ro.vendor.hiaiversion=100.151.020.100 \
    ro.vendor.treble.data_violator.disable= \
    ro.vendor.tui.service=true \
    ro.vendor.vndk.version=26.0.0 \
    use_sensorhub_labc=false \
    vendor.debug.config.mmu_en=1 \
